#!/usr/bin/env bash
set -e

tag="v1.13.2"

extension_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
tag_path="${extension_path}/dist/${tag}"
exe="gh-markdown-preview"

if [ ! -x "${tag_path}/${exe}" ]; then
  if [ "$(which go)" == "" ]; then
    echo "go must be installed to use this gh extension" >&2
    exit 1
  fi
  rm -rf "${tag_path}"
  mkdir -p "${tag_path}"
  pushd "${extension_path}" > /dev/null
  go build -o "${tag_path}/${exe}"
  popd > /dev/null
fi

exec "${tag_path}/${exe}" "$@"
